CREATE DATABASE AGROFRESH;
USE AGROFRESH;
CREATE TABLE CUSTOMER
(C_ID INT NOT NULL AUTO_INCREMENT,
FNAME VARCHAR(20) NOT NULL,
MNAME VARCHAR(20),
LNAME VARCHAR(20) NOT NULL,
GENDER CHAR(1) NOT NULL,
PHONE_NO NUMERIC(10) NOT NULL,
EMAIL VARCHAR(50),
LANDMARK VARCHAR(30) NOT NULL,
STATE VARCHAR(15) NOT NULL,
PINCODE NUMERIC(6) NOT NULL,
CONSTRAINT PK_CUS PRIMARY KEY (C_ID),
CONSTRAINT UC_CUS UNIQUE (PHONE_NO));
CREATE TABLE FARMER
(F_ID INT NOT NULL AUTO_INCREMENT,
FNAME VARCHAR(20) NOT NULL,
MNAME VARCHAR(20),
LNAME VARCHAR(20) NOT NULL,
GENDER CHAR(1) NOT NULL,
PHONE_NO NUMERIC(10) NOT NULL,
LANDMARK VARCHAR(30) NOT NULL,
STATE VARCHAR(15) NOT NULL,
PINCODE NUMERIC(6) NOT NULL,
CONSTRAINT PK_FAR PRIMARY KEY (F_ID),
CONSTRAINT UC_FAR UNIQUE (PHONE_NO));
CREATE TABLE TRANSPORT
(T_ID INT NOT NULL AUTO_INCREMENT,
AGENCY VARCHAR(20) NOT NULL,
OWNER_FNAME VARCHAR(20) NOT NULL,
OWNER_LNAME VARCHAR(20) NOT NULL,
PHONE_NO NUMERIC(10) NOT NULL,
LANDMARK VARCHAR(30) NOT NULL,
STATE VARCHAR(15) NOT NULL,
PINCODE NUMERIC(6) NOT NULL,
CONSTRAINT PK_TRP PRIMARY KEY (T_ID),
CONSTRAINT UC_TRP UNIQUE (PHONE_NO));
CREATE TABLE VEHICLE
(T_ID INT NOT NULL,
V_NAME VARCHAR(20),
V_STATE CHAR(2) NOT NULL,
V_DISTRICT_NO NUMERIC(2) NOT NULL,
V_CLASS VARCHAR(3) NOT NULL,
V_SERIAL_NO NUMERIC(4) NOT NULL,
CAPACITY NUMERIC(3) NOT NULL,
DRIVER_NAME VARCHAR(25) NOT NULL,
D_PHONE_NO NUMERIC(10) NOT NULL,
AVAIBILITY CHAR(1) DEFAULT 'Y',
CONSTRAINT PK_VHC PRIMARY KEY (D_PHONE_NO),
CONSTRAINT UC_VHC UNIQUE (V_STATE,V_DISTRICT_NO,V_CLASS,V_SERIAL_NO),
CONSTRAINT FK_TRP FOREIGN KEY (T_ID) REFERENCES TRANSPORT(T_ID) ON DELETE CASCADE);
CREATE TABLE PRODUCT
(PRCT INT NOT NULL AUTO_INCREMENT,
P_NAME VARCHAR(20),
P_PRICE NUMERIC(4),
P_NO INT NOT NULL,
CATEGORY VARCHAR(10) NOT NULL,
CONSTRAINT PK_PRDT PRIMARY KEY (PRCT),
CONSTRAINT UC_PRDT UNIQUE (CATEGORY,P_NO));
CREATE TABLE SALES_POST
(SP_ID INT NOT NULL AUTO_INCREMENT,
F_ID INT NOT NULL,
PRCT INT NOT NULL,
QUANTITY NUMERIC(3) NOT NULL,
CONSTRAINT PK_SP PRIMARY KEY (SP_ID),
CONSTRAINT UC_SP UNIQUE (F_ID,PRCT),
CONSTRAINT FK_FAR FOREIGN KEY (F_ID) REFERENCES FARMER(F_ID) ON DELETE CASCADE,
CONSTRAINT FK_PRDT_COST FOREIGN KEY (PRCT) REFERENCES PRODUCT(PRCT) ON DELETE CASCADE);
CREATE TABLE ORDERS
(O_ID INT NOT NULL AUTO_INCREMENT,
C_ID INT NOT NULL,
DELIVERY_DATE DATE NOT NULL,
ORDER_DATE DATE NOT NULL,
STATUS CHAR(1) DEFAULT 'N',
T_PRICE INT NOT NULL,
D_PHONE_NO NUMERIC(10) NOT NULL,
CONSTRAINT PK_ORD PRIMARY KEY(O_ID),
CONSTRAINT FK_CUS_ORDER FOREIGN KEY(C_ID) REFERENCES CUSTOMER(C_ID) ON DELETE CASCADE,
CONSTRAINT FK_O_V_STATE FOREIGN KEY(D_PHONE_NO) REFERENCES VEHICLE(D_PHONE_NO) ON DELETE CASCADE);
CREATE TABLE ITEM_LIST
(ITEMS INT NOT NULL AUTO_INCREMENT,
ORDER_ID INT NOT NULL,
PRICE NUMERIC(4),
F_ID INT,
PRCT INT NOT NULL,
QUANTITY NUMERIC(2) NOT NULL,
CONSTRAINT PK_IL PRIMARY KEY(ITEMS),
CONSTRAINT UC_IL UNIQUE (ORDER_ID,PRCT,F_ID),
CONSTRAINT FK_IL_F_ID FOREIGN KEY (F_ID) REFERENCES FARMER(F_ID) ON DELETE CASCADE,
CONSTRAINT FK_IL_CATEGORY FOREIGN KEY (PRCT) REFERENCES PRODUCT(PRCT) ON DELETE CASCADE);
CREATE TABLE DELIVERY
(D_NO INT NOT NULL AUTO_INCREMENT,
D_PHONE_NO NUMERIC(10) NOT NULL,
C_LOC VARCHAR(20) NOT NULL,
D_LOC VARCHAR(20) NOT NULL,
DISTANCE INT,
COST INT NOT NULL,
CONSTRAINT PK_DEL PRIMARY KEY (D_NO),
CONSTRAINT FK_O_V_SRNO FOREIGN KEY(D_PHONE_NO) REFERENCES VEHICLE(D_PHONE_NO) ON DELETE CASCADE);
CREATE TABLE ADMIN
(PHONE_NO NUMERIC(10) NOT NULL,
PASS_WORD VARCHAR(20) NOT NULL,
USER_TABLE CHAR(1) NOT NULL,
U_ID INT NOT NULL,
CONSTRAINT PK_ADMIN PRIMARY KEY(PHONE_NO));
